apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: author-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/grpc-microservices
            - name: NODE_ENV
              value: production