apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service:latest
          ports:
            - containerPort: 50052
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/grpc-microservices
            - name: AUTHOR_SERVICE_URL
              value: author-service:50051
            - name: NODE_ENV
              value: production