name: Create Diagram
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: githubocto/repo-visualizer@v1
        with:
          output: diagram.svg
```[_{{{CITATION{{{_1{Visualizing a Codebase - GitHub Next](https://githubnext.com/projects/repo-visualization/)

